### ISSUE TITLE
Two Repos

### ISSUE THREAD

**Issue by ghost** [presidential-innovation-fellows/midaas-api#1]
@michael-balint Hi Michael was just curious to know that there are two repos for MIDAAS.Powered by two different stacks 
This project uses serverless (a framework based upon AWS Lambda and API Gateway). Please consult the serverless docs for more information on running locally and deploying.
https://github.com/CommerceDataService/midaas-api
and @commercegov his project uses an Express.js application and an AWS Redshift database. 
Do both do the same thing.Also I am in the process of building one in Canada.I was interested in knowing which datasets are mostly required for this.

**Comment by michael-balint** [comment]
Hi @neilmartis! Both are essentially the same thing. This repo (presidential-innovation-fellows/midaas-api) houses a prototype built using serverless. The Commerce Data Service team ported my prototype to node/express.

Both repos use [American Community Survey](https://www.census.gov/programs-surveys/acs/data/pums.html) data. The Commerce Data Service's repo (which you referenced) has more info in the readme (and is more up-to-date).

Hope that helps - good luck with your work!

**Comment by ghost** [comment]
Thanks Michael for the info
