### ISSUE TITLE
Help Required

### ISSUE THREAD

**Issue by ghost** [presidential-innovation-fellows/midaas-api#2]
@michael-balint Hi Michael I was interested in knowing which were the datasets are used to create a similiar API for Canada and none right now which can be integrated in the #HackThePayGap application. Amy ideas I do the MIDAAS APi is based on the ACS survey however will census data be of any good or what kind of dataset I need to look for. Thank you for the earlier help and have a great day

**Comment by michael-balint** [comment]
Hi @neilmartis - not sure I understand the question... is it which are complementary Canadian datasets? If so, I think looking here would be a good starting point: http://www12.statcan.gc.ca/census-recensement/index-eng.cfm.

**Comment by ghost** [comment]
@michael-balint Hi Michael I am trying to replicate the same system for Canada but I have know idea which dataset can be used as Canada's survey information is not published on Open Gov Canada and most of the Data sets are old. Any idea which data set should I look for when asking people as I want to do for the #HackThePayGap teams which I am a part of and can be used both in Canada and US. I am a part of Aware with Steven,Margaret & Lyndsey

**Comment by ghost** [comment]
@michael-balint I have spoken to couple of folks from the government of canada but I need to tell them which datasets are required for MIDAAS.I understood the tech part of things

**Comment by ghost** [comment]
@michael-balint Sorry for the trouble and confusion

**Comment by michael-balint** [comment]
If I were you, I'd ask them for the equivalent of the ACS PUMS data that was used. At minimum you need data on the population broken down by geography (for ACS this is PUMA codes), age, race, sex, and income. MIDAAS has since also added information for job types.

**Comment by ghost** [comment]
@michael-balint Thank you will keep you posted.
